const SUPABASE_URL='https://tqkbehwjylktpfrguvlr.supabase.co';
const SUPABASE_KEY='sb_publishable_wEXNa9FnRzI7iU_uMVwiLQ_NsFuDwff';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const brDate=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR'):'';
const initials=n=>(n||'?').trim().slice(0,1).toUpperCase();
let activeSeason=null,publicPeople=[],publicMatches=[],publicMatchPlayers=[],publicGoals=[];
const rankingData={pontos:[],melhores:[],piores:[]};

function baseHeaders(token){return {apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}}
async function rest(path,opts={}){const res=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method:opts.method||'GET',headers:{...baseHeaders(opts.token),Accept:'application/json',...(opts.prefer?{Prefer:opts.prefer}:{}),...(opts.headers||{})},body:opts.body===undefined?undefined:JSON.stringify(opts.body)});if(!res.ok)throw new Error((await res.text())||`Erro ${res.status}`);const t=await res.text();return t?JSON.parse(t):null}

$$('#mainNav button').forEach(btn=>btn.onclick=()=>{$$('#mainNav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.panel').forEach(v=>v.classList.remove('active'));$('#'+btn.dataset.view).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})});

function identityMark(r){if(r?.badge_url)return `<span class="flag badge"><img src="${esc(r.badge_url)}" alt=""></span>`;return `<span class="flag">${esc(r?.flag_emoji||'⚽')}</span>`}
function avatarHtml(p,identity=null){return `<div class="avatar">${p?.photo_url?`<img src="${esc(p.photo_url)}">`:esc(initials(p?.name))}${identityMark(identity||p)}</div>`}
function rankingRows(rows,type){return rows.length?rows.map((r,i)=>`<div class="row"><div class="pos">${i+1}</div>${avatarHtml(r,r)}<div class="info"><strong>${esc(r.name)}</strong><div class="meta">${esc(r.selection_name||'Sem time/seleção')}</div></div><div class="score">${type==='points'?`${r.points||0} pts`:type==='best'?`${r.best_count||0}x`:`${r.worst_count||0}x`}</div></div>`).join(''):'<div class="empty compact">Ainda não há nomes neste ranking.</div>'}
function renderRankings(){
  $('#pointsList').innerHTML=rankingRows(rankingData.pontos,'points');
  $('#bestList').innerHTML=rankingRows((rankingData.melhores||[]).filter(r=>(r.best_count||0)>0),'best');
  $('#worstList').innerHTML=rankingRows((rankingData.piores||[]).filter(r=>(r.worst_count||0)>0),'worst');
}
function renderScorers(rows){const scorers=(rows||[]).filter(r=>(r.goals||0)>0);$('#scorersList').innerHTML=scorers.length?scorers.map((r,i)=>`<div class="row"><div class="pos">${i+1}</div>${avatarHtml(r,r)}<div class="info"><strong>${esc(r.name)}</strong><div class="meta">${esc(r.selection_name||'Sem time/seleção')}</div></div><div class="score">${r.goals} ${r.goals===1?'gol':'gols'}</div></div>`).join(''):'<div class="empty">Nenhum gol registrado ainda.</div>'}
function renderFeed(){const map=Object.fromEntries(publicPeople.map(p=>[p.id,p]));const highlighted=publicMatches.filter(m=>m.best_person_id||m.worst_person_id);$('#feedHistory').className='';$('#feedHistory').innerHTML=highlighted.length?highlighted.map(m=>{const best=map[m.best_person_id],worst=map[m.worst_person_id];const cards=[];if(m.best_person_id)cards.push(`<article class="feedcard"><div class="photo">${m.best_photo_url?`<img src="${esc(m.best_photo_url)}">`:'FOTO DO MELHOR'}</div><div class="feedbody"><div class="tag">🏆 MELHOR DO DOMINGO</div><h3>${esc(best?.name||'Jogador')}</h3><p class="caption">${esc(m.best_caption||'Sem resenha publicada.')}</p></div></article>`);if(m.worst_person_id)cards.push(`<article class="feedcard"><div class="photo">${m.worst_photo_url?`<img src="${esc(m.worst_photo_url)}">`:'FOTO DO PIOR'}</div><div class="feedbody"><div class="tag">😅 PIOR DO DOMINGO</div><h3>${esc(worst?.name||'Jogador')}</h3><p class="caption">${esc(m.worst_caption||'Sem resenha publicada.')}</p></div></article>`);return `<div class="feedround"><div class="rounddate">${brDate(m.played_on)} • ⚫ ${m.black_score} × ${m.red_score} 🔴</div><div class="feedgrid">${cards.join('')}</div></div>`}).join(''):'<div class="empty">Nenhum melhor ou pior publicado ainda.</div>'}
function renderMatches(){const pmap=Object.fromEntries(publicPeople.map(p=>[p.id,p]));$('#matchesList').innerHTML=publicMatches.length?publicMatches.map(m=>{const mps=publicMatchPlayers.filter(x=>x.match_id===m.id);const black=mps.filter(x=>x.team==='black').map(x=>pmap[x.person_id]?.name).filter(Boolean);const red=mps.filter(x=>x.team==='red').map(x=>pmap[x.person_id]?.name).filter(Boolean);const gs=publicGoals.filter(g=>g.match_id===m.id&&g.quantity>0).map(g=>`${pmap[g.scorer_person_id]?.name||'Jogador'} (${g.quantity})`);return `<article class="match"><div class="matchhead"><span>${brDate(m.played_on)}</span><span>Domingo • 7h</span></div><div class="scoreline"><div class="team">⚫ PRETO</div><div class="bigscore">${m.black_score} × ${m.red_score}</div><div class="team right">VERMELHO 🔴</div></div><div class="details"><div><b>Preto:</b> ${esc(black.join(', ')||'—')}</div><div><b>Vermelho:</b> ${esc(red.join(', ')||'—')}</div><div><b>Gols:</b> ${esc(gs.join(', ')||'Nenhum registrado')}</div></div></article>`}).join(''):'<div class="empty">Nenhuma partida publicada ainda.</div>'}
function renderGallery(rows){$('#galleryList').innerHTML=rows.length?rows.map(i=>i.type==='photo'?`<div class="tile" style="background-image:linear-gradient(0deg,rgba(0,0,0,.75),rgba(0,0,0,.05)),url('${esc(i.media_url)}')"><span>${esc(i.caption||'Foto da pelada')}</span></div>`:`<div class="tile"><video src="${esc(i.media_url)}" controls preload="metadata"></video><span>${esc(i.caption||'Vídeo')}</span></div>`).join(''):'<div class="empty" style="grid-column:1/-1">Nenhuma foto ou vídeo publicado ainda.</div>'}

async function loadPublicData(){try{const seasons=await rest('seasons?is_active=eq.true&select=id,year,name&limit=1');activeSeason=seasons?.[0];if(!activeSeason)return;$('#ranking .eyebrow').textContent=`TEMPORADA ${activeSeason.year}`;const [points,best,worst,scorers,matches,people,mps,goals,gallery]=await Promise.all([rest(`v_points_ranking?season_id=eq.${activeSeason.id}&select=*&order=points.desc,name.asc`),rest(`v_best_ranking?season_id=eq.${activeSeason.id}&select=*&order=best_count.desc,name.asc`),rest(`v_worst_ranking?season_id=eq.${activeSeason.id}&select=*&order=worst_count.desc,name.asc`),rest(`v_scorers?season_id=eq.${activeSeason.id}&select=*&order=goals.desc,name.asc`),rest(`matches?season_id=eq.${activeSeason.id}&status=eq.published&select=*&order=played_on.desc`),rest('people?active=eq.true&select=id,name,photo_url,type'),rest('match_players?select=*'),rest('goals?select=*'),rest('gallery_items?published=eq.true&select=*&order=created_at.desc')]);rankingData.pontos=points;rankingData.melhores=best;rankingData.piores=worst;publicMatches=matches;publicPeople=people;publicMatchPlayers=mps;publicGoals=goals;renderRankings();renderScorers(scorers);renderFeed();renderMatches();renderGallery(gallery)}catch(e){console.error(e)}}
loadPublicData();