import { trpc } from "@/lib/trpc";
import { BarChart3, CalendarDays, Check, ChevronLeft, CircleUserRound, LoaderCircle, LogOut, Pencil, Search, ShieldCheck, Trophy, Upload, UserPlus, UsersRound } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

type Tab = "informacoes" | "jogadores" | "partida" | "destaques" | "galeria" | "editar" | "acessos";
type TeamColor = "black" | "red";
type PlayerType = "fixed" | "guest";

const tabs = [
  { id: "informacoes" as const, label: "Informações", icon: BarChart3 }, { id: "jogadores" as const, label: "Jogadores", icon: UsersRound }, { id: "partida" as const, label: "Partida", icon: CalendarDays }, { id: "destaques" as const, label: "Melhor/Pior", icon: Trophy }, { id: "galeria" as const, label: "Galeria", icon: Upload }, { id: "editar" as const, label: "Temporada", icon: Pencil }, { id: "acessos" as const, label: "Acessos", icon: ShieldCheck },
];

function dateInput(value?: string | Date | null) {
  if (!value) return "";
  const date = new Date(value);
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}

async function fileToBase64(file: File) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error("Não foi possível ler o arquivo."));
    reader.onload = () => resolve(String(reader.result));
    reader.readAsDataURL(file);
  });
}

function PanelFrame({ children }: { children: React.ReactNode }) {
  return <div className="admin-app"><header className="admin-header"><div className="club-container"><div className="admin-header__identity"><ShieldCheck size={18} /><span>AMIGOS F.C.<small>Painel administrativo</small></span></div><Link href="/" className="admin-site-link"><ChevronLeft size={16} /> Voltar ao site</Link></div></header><section className="admin-hero"><div className="club-container"><p className="section-label">Área da organização</p><h1>Painel do <strong>AMIGOS</strong></h1></div></section>{children}</div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="admin-field"><span>{label}</span>{children}</label>; }
function FormCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="admin-card"><h2>{title}</h2>{children}</section>; }
function SaveButton({ children, saving }: { children: React.ReactNode; saving?: boolean }) { return <button className="admin-save" type="submit" disabled={saving}>{saving && <LoaderCircle size={17} className="spin" />}{children}</button>; }

function AdminLogin() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const utils = trpc.useUtils(); const login = trpc.adminAuth.login.useMutation();
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const admin = await login.mutateAsync({ email, password }); utils.adminAuth.me.setData(undefined, admin); await utils.admin.data.invalidate(); window.location.assign("/painel"); } catch (error: any) { toast.error(error.message || "E-mail ou senha inválidos."); } };
  return <PanelFrame><section className="section"><div className="club-container"><div className="admin-login"><div className="admin-login__symbol"><ShieldCheck size={30} /></div><div><p className="section-label">Acesso protegido</p><h2>Entrar no painel</h2><p>Somente administradores autorizados podem lançar partidas, editar dados ou publicar a resenha.</p></div><form className="admin-form" onSubmit={submit}><Field label="E-mail"><input type="email" required autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="seuemail@exemplo.com" /></Field><Field label="Senha"><input type="password" required minLength={8} autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)} placeholder="Sua senha" /></Field><SaveButton saving={login.isPending}>Entrar no painel</SaveButton></form></div></div></section></PanelFrame>;
}

function PlayerForm({ data, onComplete, editing, clearEditing }: { data: any; onComplete: () => void; editing: any | null; clearEditing: () => void }) {
  const [name, setName] = useState(""); const [position, setPosition] = useState(""); const [type, setType] = useState<PlayerType>("fixed"); const [active, setActive] = useState(true); const [entityId, setEntityId] = useState<string>(""); const [entityTerm, setEntityTerm] = useState(""); const [entityCandidate, setEntityCandidate] = useState<any | null>(null); const [avatar, setAvatar] = useState<File | null>(null);
  const utils = trpc.useUtils();
  const badgeSearch = trpc.admin.searchBadge.useQuery({ term: entityTerm || "--" }, { enabled: entityTerm.trim().length >= 2 });
  const saveEntity = trpc.admin.saveEntity.useMutation(); const savePlayer = trpc.admin.savePlayer.useMutation(); const upload = trpc.admin.uploadMedia.useMutation();
  const badgeOptions = badgeSearch.data ?? [];
  useEffect(() => { if (!editing) return; setName(editing.name); setPosition(editing.position || ""); setType(editing.participantType); setActive(editing.isActive); const registration = data.registrations.find((item: any) => item.playerId === editing.id && item.seasonId === data.activeSeason?.id); const savedEntity = data.entities.find((entity: any) => entity.id === registration?.footballEntityId); setEntityId(registration?.footballEntityId ? String(registration.footballEntityId) : ""); setEntityTerm(savedEntity?.name || ""); setEntityCandidate(savedEntity || null); setAvatar(null); }, [editing, data]);
  const savedEntity = data.entities.find((entity: any) => String(entity.id) === entityId);
  const selectedEntity = savedEntity || entityCandidate || badgeOptions[0] || null;
  const submit = async (event: FormEvent) => { event.preventDefault(); if (type === "fixed" && !data.activeSeason) return toast.error("Crie a temporada antes de cadastrar um jogador fixo."); const entityToSave = entityCandidate || badgeOptions[0] || null; if (type === "fixed" && !entityId && !entityToSave) return toast.error("Digite o time ou seleção e aguarde uma sugestão de escudo ou bandeira."); try { let avatarUrl = editing?.avatarUrl ?? null; if (avatar) avatarUrl = (await upload.mutateAsync({ base64: await fileToBase64(avatar), fileName: avatar.name, mimeType: avatar.type || "image/jpeg", folder: "avatars" })).url; const footballEntityId = type === "fixed" ? (entityId ? Number(entityId) : await saveEntity.mutateAsync(entityToSave!)) : null; await savePlayer.mutateAsync({ id: editing?.id, name, position, participantType: type, isActive: active, avatarUrl, seasonId: type === "fixed" ? data.activeSeason?.id ?? null : null, footballEntityId }); await utils.admin.data.invalidate(); onComplete(); clearEditing(); setName(""); setPosition(""); setEntityTerm(""); setEntityId(""); setEntityCandidate(null); setAvatar(null); toast.success(editing ? "Jogador atualizado." : "Jogador cadastrado."); } catch (error: any) { toast.error(error.message || "Não foi possível salvar o jogador."); } };
  const saving = savePlayer.isPending || saveEntity.isPending || upload.isPending;
  return <FormCard title={editing ? "Editar jogador" : "Novo jogador"}><form className="admin-form" onSubmit={submit}><div className="admin-form__grid"><Field label="Nome"><input required value={name} onChange={event => setName(event.target.value)} placeholder="Nome do jogador" /></Field><Field label="Posição (opcional)"><input value={position} maxLength={80} onChange={event => setPosition(event.target.value)} placeholder="Ex.: Goleiro, lateral, volante" /></Field><Field label="Tipo"><select value={type} onChange={event => setType(event.target.value as PlayerType)}><option value="fixed">Jogador fixo</option><option value="guest">Convidado</option></select></Field><Field label="Situação"><select value={active ? "active" : "inactive"} onChange={event => setActive(event.target.value === "active")}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></Field><Field label="Foto (opcional)"><input type="file" accept="image/*" onChange={event => setAvatar(event.target.files?.[0] || null)} /></Field></div>{type === "fixed" && <div className="entity-picker"><Field label="Time ou seleção"><input required value={entityTerm} onChange={event => { setEntityTerm(event.target.value); setEntityId(""); setEntityCandidate(null); }} placeholder="Ex.: Brasil, Flamengo, Barcelona" /></Field><div className="automatic-badge">{badgeSearch.isFetching ? <><LoaderCircle className="spin" size={18} /><span>Localizando escudo ou bandeira...</span></> : selectedEntity ? <>{selectedEntity.badgeUrl ? <img src={selectedEntity.badgeUrl} alt="" /> : <Trophy size={19} />}<span>{selectedEntity.name}</span><small>{selectedEntity.category === "national_team" ? "Bandeira identificada automaticamente" : "Escudo identificado automaticamente"}</small></> : entityTerm.trim().length >= 2 ? <><Search size={18} /><span>Nenhum símbolo encontrado ainda.</span></> : <><Search size={18} /><span>O escudo ou a bandeira será encontrado automaticamente.</span></>}</div></div>}<div className="admin-actions"><SaveButton saving={saving}>{editing ? "Salvar alterações" : "Cadastrar jogador"}</SaveButton>{editing && <button type="button" className="admin-secondary" onClick={clearEditing}>Cancelar</button>}</div></form></FormCard>;
}

function PlayersTab({ data }: { data: any }) {
  const [editing, setEditing] = useState<any | null>(null); const utils = trpc.useUtils();
  const entityFor = (playerId: number) => { const registration = data.registrations.find((item: any) => item.playerId === playerId && item.seasonId === data.activeSeason?.id); return data.entities.find((entity: any) => entity.id === registration?.footballEntityId); };
  return <div className="admin-two-column"><PlayerForm data={data} editing={editing} clearEditing={() => setEditing(null)} onComplete={() => utils.admin.data.invalidate()} /><FormCard title="Elenco cadastrado"><div className="admin-player-list">{data.players.length ? data.players.map((player: any) => { const entity = entityFor(player.id); return <div className="admin-player" key={player.id}><div><span className="admin-player-avatar-stack">{player.avatarUrl ? <img src={player.avatarUrl} alt="" /> : <CircleUserRound />}{entity?.badgeUrl && <span className="admin-player-symbol"><img src={entity.badgeUrl} alt="" /></span>}</span><span><strong>{player.name}</strong><small>{player.participantType === "fixed" ? "Jogador fixo" : "Convidado"} · {player.isActive ? "Ativo" : "Inativo"}</small>{player.position && <small className="admin-player-position">{player.position}</small>}{entity?.name && <small className="admin-player-team">{entity.name}</small>}</span></div><button type="button" onClick={() => setEditing(player)} aria-label={`Editar ${player.name}`}><Pencil size={16} /></button></div>; }) : <p className="admin-muted">Cadastre o elenco para começar a lançar as partidas.</p>}</div></FormCard></div>;
}

function MatchTab({ data }: { data: any }) {
  const [editingId, setEditingId] = useState<string>(""); const [matchDate, setMatchDate] = useState(dateInput(new Date())); const [blackScore, setBlackScore] = useState("0"); const [redScore, setRedScore] = useState("0"); const [notes, setNotes] = useState(""); const [blackIds, setBlackIds] = useState<number[]>([]); const [redIds, setRedIds] = useState<number[]>([]); const [goals, setGoals] = useState<Record<number, string>>({});
  const utils = trpc.useUtils(); const saveMatch = trpc.admin.saveMatch.useMutation();
  const activePlayers = data.players.filter((player: any) => player.isActive);
  useEffect(() => { const selected = data.matches.find((match: any) => String(match.id) === editingId); if (!selected) return; setMatchDate(dateInput(selected.matchDate)); setBlackScore(String(selected.blackScore)); setRedScore(String(selected.redScore)); setNotes(selected.notes || ""); setBlackIds(selected.participants.filter((item: any) => item.teamColor === "black").map((item: any) => item.playerId)); setRedIds(selected.participants.filter((item: any) => item.teamColor === "red").map((item: any) => item.playerId)); setGoals(Object.fromEntries(selected.goals.map((goal: any) => [goal.playerId, String(goal.quantity)]))); }, [editingId, data.matches]);
  const assign = (playerId: number, team: TeamColor) => { if (team === "black") { setBlackIds(ids => ids.includes(playerId) ? ids.filter(id => id !== playerId) : [...ids, playerId]); setRedIds(ids => ids.filter(id => id !== playerId)); } else { setRedIds(ids => ids.includes(playerId) ? ids.filter(id => id !== playerId) : [...ids, playerId]); setBlackIds(ids => ids.filter(id => id !== playerId)); } };
  const participants = [...blackIds, ...redIds];
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!data.activeSeason) return toast.error("Crie uma temporada antes de registrar uma partida."); if (participants.length < 2) return toast.error("Escale ao menos dois jogadores."); try { await saveMatch.mutateAsync({ id: editingId ? Number(editingId) : undefined, seasonId: data.activeSeason.id, matchDate, blackScore: Number(blackScore), redScore: Number(redScore), notes: notes || null, participants: [...blackIds.map(playerId => ({ playerId, teamColor: "black" as const })), ...redIds.map(playerId => ({ playerId, teamColor: "red" as const }))], goals: participants.map(playerId => ({ playerId, quantity: Math.max(0, Number(goals[playerId] || 0)) })) }); await utils.club.publicData.invalidate(); await utils.admin.data.invalidate(); toast.success(editingId ? "Partida corrigida e rankings recalculados." : "Partida registrada e rankings atualizados."); setEditingId(""); setBlackIds([]); setRedIds([]); setGoals({}); setBlackScore("0"); setRedScore("0"); setNotes(""); } catch (error: any) { toast.error(error.message || "Não foi possível salvar a partida."); } };
  return <FormCard title="Lançar partida"><form className="admin-form" onSubmit={submit}><div className="admin-form__grid admin-form__grid--four"><Field label="Editar partida"><select value={editingId} onChange={event => setEditingId(event.target.value)}><option value="">Nova partida</option>{data.matches.map((match: any) => <option key={match.id} value={match.id}>{dateInput(match.matchDate)} · Preto {match.blackScore} × {match.redScore} Vermelho</option>)}</select></Field><Field label="Data"><input required type="date" value={matchDate} onChange={event => setMatchDate(event.target.value)} /></Field><Field label="Gols do Preto"><input type="number" min="0" value={blackScore} onChange={event => setBlackScore(event.target.value)} /></Field><Field label="Gols do Vermelho"><input type="number" min="0" value={redScore} onChange={event => setRedScore(event.target.value)} /></Field></div><Field label="Observação (opcional)"><textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Uma anotação curta sobre o domingo." /></Field><div className="team-builder"><div className="team-builder__header"><span>Time Preto</span><small>{blackIds.length} jogadores</small></div>{activePlayers.map((player: any) => <button type="button" key={player.id} className={blackIds.includes(player.id) ? "selected" : ""} onClick={() => assign(player.id, "black")}>{player.name}<small>{player.participantType === "guest" ? "Convidado" : "Fixo"}</small></button>)}</div><div className="team-builder team-builder--red"><div className="team-builder__header"><span>Time Vermelho</span><small>{redIds.length} jogadores</small></div>{activePlayers.map((player: any) => <button type="button" key={player.id} className={redIds.includes(player.id) ? "selected" : ""} onClick={() => assign(player.id, "red")}>{player.name}<small>{player.participantType === "guest" ? "Convidado" : "Fixo"}</small></button>)}</div>{participants.length > 0 && <div className="goals-builder"><h3>Gols da partida</h3><p>Somente quem está escalado aparece aqui.</p><div>{participants.map(id => { const player = activePlayers.find((entry: any) => entry.id === id); return <Field label={player?.name || "Jogador"} key={id}><input type="number" min="0" value={goals[id] || "0"} onChange={event => setGoals(value => ({ ...value, [id]: event.target.value }))} /></Field>; })}</div></div>}<SaveButton saving={saveMatch.isPending}>{editingId ? "Salvar correção" : "Salvar partida"}</SaveButton></form></FormCard>;
}

function HighlightsTab({ data }: { data: any }) {
  const [matchId, setMatchId] = useState(""); const [bestId, setBestId] = useState(""); const [worstId, setWorstId] = useState(""); const [bestCaption, setBestCaption] = useState(""); const [worstCaption, setWorstCaption] = useState(""); const [bestFile, setBestFile] = useState<File | null>(null); const [worstFile, setWorstFile] = useState<File | null>(null);
  const selectedMatch = data.matches.find((match: any) => String(match.id) === matchId); const saveHighlight = trpc.admin.saveHighlight.useMutation(); const upload = trpc.admin.uploadMedia.useMutation(); const utils = trpc.useUtils();
  useEffect(() => { if (!selectedMatch) return; const best = selectedMatch.highlights.find((item: any) => item.kind === "best"); const worst = selectedMatch.highlights.find((item: any) => item.kind === "worst"); setBestId(best?.playerId ? String(best.playerId) : ""); setWorstId(worst?.playerId ? String(worst.playerId) : ""); setBestCaption(best?.caption || ""); setWorstCaption(worst?.caption || ""); setBestFile(null); setWorstFile(null); }, [matchId, selectedMatch]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!matchId || (!bestId && !worstId)) return toast.error("Selecione a partida e ao menos um destaque."); try { const existingBest = selectedMatch?.highlights.find((item: any) => item.kind === "best"); const existingWorst = selectedMatch?.highlights.find((item: any) => item.kind === "worst"); if (bestId) { const imageUrl = bestFile ? (await upload.mutateAsync({ base64: await fileToBase64(bestFile), fileName: bestFile.name, mimeType: bestFile.type || "image/jpeg", folder: "highlights" })).url : existingBest?.imageUrl ?? null; await saveHighlight.mutateAsync({ matchId: Number(matchId), kind: "best", playerId: Number(bestId), imageUrl, caption: bestCaption || null }); } if (worstId) { const imageUrl = worstFile ? (await upload.mutateAsync({ base64: await fileToBase64(worstFile), fileName: worstFile.name, mimeType: worstFile.type || "image/jpeg", folder: "highlights" })).url : existingWorst?.imageUrl ?? null; await saveHighlight.mutateAsync({ matchId: Number(matchId), kind: "worst", playerId: Number(worstId), imageUrl, caption: worstCaption || null }); } await utils.club.publicData.invalidate(); await utils.admin.data.invalidate(); toast.success("Destaques e resenhas salvos."); } catch (error: any) { toast.error(error.message || "Não foi possível salvar os destaques."); } };
  return <FormCard title="Melhor e pior da rodada"><form className="admin-form" onSubmit={submit}><Field label="Partida"><select required value={matchId} onChange={event => setMatchId(event.target.value)}><option value="">Escolha a partida</option>{data.matches.map((match: any) => <option value={match.id} key={match.id}>{dateInput(match.matchDate)} · Preto {match.blackScore} × {match.redScore} Vermelho</option>)}</select></Field>{selectedMatch && <div className="highlight-form"><div><h3>Melhor da rodada</h3><Field label="Jogador"><select value={bestId} onChange={event => setBestId(event.target.value)}><option value="">Escolher jogador</option>{selectedMatch.participants.map((item: any) => <option value={item.playerId} key={item.id}>{item.player.name}</option>)}</select></Field><Field label="Foto"><input type="file" accept="image/*" onChange={event => setBestFile(event.target.files?.[0] || null)} /></Field><Field label="Resenha"><textarea value={bestCaption} onChange={event => setBestCaption(event.target.value)} placeholder="Hoje resolveu jogar bola..." /></Field></div><div><h3>Pior da rodada</h3><Field label="Jogador"><select value={worstId} onChange={event => setWorstId(event.target.value)}><option value="">Escolher jogador</option>{selectedMatch.participants.map((item: any) => <option value={item.playerId} key={item.id}>{item.player.name}</option>)}</select></Field><Field label="Foto"><input type="file" accept="image/*" onChange={event => setWorstFile(event.target.files?.[0] || null)} /></Field><Field label="Resenha"><textarea value={worstCaption} onChange={event => setWorstCaption(event.target.value)} placeholder="Hoje a bola pediu para sair..." /></Field></div></div>}<SaveButton saving={saveHighlight.isPending || upload.isPending}>Salvar destaques</SaveButton></form></FormCard>;
}

function GalleryTab({ data }: { data: any }) {
  const [editingId, setEditingId] = useState(""); const [matchId, setMatchId] = useState(""); const [date, setDate] = useState(dateInput(new Date())); const [caption, setCaption] = useState(""); const [file, setFile] = useState<File | null>(null); const upload = trpc.admin.uploadMedia.useMutation(); const save = trpc.admin.saveGalleryItem.useMutation(); const utils = trpc.useUtils();
  const existingItem = data.gallery.find((item: any) => String(item.id) === editingId);
  useEffect(() => { if (!existingItem) return; setMatchId(existingItem.matchId ? String(existingItem.matchId) : ""); setDate(dateInput(existingItem.capturedAt)); setCaption(existingItem.caption || ""); setFile(null); }, [editingId, existingItem]);
  const clearForm = () => { setEditingId(""); setMatchId(""); setDate(dateInput(new Date())); setCaption(""); setFile(null); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!file && !existingItem) return toast.error("Escolha uma foto ou vídeo."); try { const uploaded = file ? await upload.mutateAsync({ base64: await fileToBase64(file), fileName: file.name, mimeType: file.type || "image/jpeg", folder: "gallery" }) : null; const mediaType = uploaded ? (file!.type.startsWith("video/") ? "video" : "image") : existingItem.mediaType; await save.mutateAsync({ id: editingId ? Number(editingId) : undefined, seasonId: data.activeSeason?.id ?? null, matchId: matchId ? Number(matchId) : null, mediaType, mediaUrl: uploaded?.url || existingItem.mediaUrl, mediaKey: uploaded?.key || existingItem.mediaKey || null, caption: caption || null, capturedAt: date }); await utils.club.publicData.invalidate(); await utils.admin.data.invalidate(); clearForm(); toast.success(editingId ? "Publicação atualizada." : "Conteúdo adicionado à galeria."); } catch (error: any) { toast.error(error.message || "Não foi possível salvar a galeria."); } };
  return <FormCard title={editingId ? "Editar publicação" : "Adicionar à galeria"}><form className="admin-form" onSubmit={submit}><div className="admin-form__grid"><Field label="Publicação"><select value={editingId} onChange={event => setEditingId(event.target.value)}><option value="">Nova publicação</option>{data.gallery.map((item: any) => <option key={item.id} value={item.id}>{dateInput(item.capturedAt)} · {(item.caption || "Sem legenda").slice(0, 32)}</option>)}</select></Field><Field label="Data"><input required type="date" value={date} onChange={event => setDate(event.target.value)} /></Field><Field label="Vincular a partida"><select value={matchId} onChange={event => setMatchId(event.target.value)}><option value="">Sem vínculo</option>{data.matches.map((match: any) => <option key={match.id} value={match.id}>{dateInput(match.matchDate)} · Preto {match.blackScore} × {match.redScore} Vermelho</option>)}</select></Field><Field label={editingId ? "Trocar foto ou vídeo" : "Foto ou vídeo"}><input required={!editingId} type="file" accept="image/*,video/*" onChange={event => setFile(event.target.files?.[0] || null)} /></Field></div><Field label="Legenda"><textarea value={caption} onChange={event => setCaption(event.target.value)} placeholder="Aquela resenha depois do jogo..." /></Field><div className="admin-actions"><SaveButton saving={upload.isPending || save.isPending}><Upload size={17} /> {editingId ? "Salvar publicação" : "Publicar na galeria"}</SaveButton>{editingId && <button type="button" className="admin-secondary" onClick={clearForm}>Cancelar</button>}</div></form></FormCard>;
}

function EditTab({ data }: { data: any }) {
  const [name, setName] = useState(data.activeSeason?.name || `Temporada ${new Date().getFullYear()}`); const [year, setYear] = useState(String(data.activeSeason?.year || new Date().getFullYear())); const [label, setLabel] = useState(data.activeSeason?.competitionLabel || "Pontos corridos"); const createSeason = trpc.admin.createSeason.useMutation(); const utils = trpc.useUtils();
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await createSeason.mutateAsync({ name, year: Number(year), competitionLabel: label }); await utils.admin.data.invalidate(); await utils.club.publicData.invalidate(); toast.success("Temporada ativada."); } catch (error: any) { toast.error(error.message || "Não foi possível salvar a temporada."); } };
  return <div className="admin-two-column"><FormCard title="Temporada ativa"><form className="admin-form" onSubmit={submit}><div className="admin-form__grid"><Field label="Nome"><input required value={name} onChange={event => setName(event.target.value)} /></Field><Field label="Ano"><input required type="number" min="2011" max="2100" value={year} onChange={event => setYear(event.target.value)} /></Field><Field label="Formato"><input required value={label} onChange={event => setLabel(event.target.value)} /></Field></div><SaveButton saving={createSeason.isPending}><Trophy size={17} /> Ativar temporada</SaveButton></form></FormCard><FormCard title="Correções"><p className="admin-muted">Para corrigir uma escalação, placar ou gols, abra a aba <strong>Partida</strong> e escolha o jogo no campo “Editar partida”. Para alterar as resenhas, abra <strong>Melhor/Pior</strong> e escolha a rodada.</p></FormCard></div>;
}

function AccessTab() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const utils = trpc.useUtils(); const accounts = trpc.admin.access.list.useQuery(); const create = trpc.admin.access.create.useMutation(); const setActive = trpc.admin.access.setActive.useMutation();
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await create.mutateAsync({ name, email, password }); setName(""); setEmail(""); setPassword(""); await utils.admin.access.list.invalidate(); toast.success("Administrador autorizado."); } catch (error: any) { toast.error(error.message || "Não foi possível adicionar este acesso."); } };
  const toggle = async (account: any) => { try { await setActive.mutateAsync({ id: account.id, isActive: !account.isActive }); await utils.admin.access.list.invalidate(); toast.success(account.isActive ? "Acesso desativado." : "Acesso reativado."); } catch (error: any) { toast.error(error.message || "Não foi possível atualizar este acesso."); } };
  return <div className="admin-two-column"><FormCard title="Novo administrador"><form className="admin-form" onSubmit={submit}><Field label="Nome"><input required value={name} onChange={event => setName(event.target.value)} placeholder="Nome do administrador" /></Field><Field label="E-mail"><input required type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="email@exemplo.com" /></Field><Field label="Senha inicial"><input required type="password" minLength={8} value={password} onChange={event => setPassword(event.target.value)} placeholder="Mínimo de 8 caracteres" /></Field><SaveButton saving={create.isPending}><UserPlus size={17} /> Autorizar acesso</SaveButton></form></FormCard><FormCard title="Acessos autorizados"><div className="admin-player-list">{accounts.data?.map((account: any) => <div className="admin-player" key={account.id}><div><span className="admin-access-icon"><UsersRound size={19} /></span><span><strong>{account.name}</strong><small>{account.email}</small><small className={account.isActive ? "admin-access-active" : "admin-access-off"}>{account.isActive ? "Acesso ativo" : "Acesso desativado"}</small></span></div><button type="button" onClick={() => toggle(account)} disabled={setActive.isPending} title={account.isActive ? "Desativar acesso" : "Reativar acesso"}>{account.isActive ? <LogOut size={16} /> : <Check size={16} />}</button></div>) || <p className="admin-muted">Carregando os acessos autorizados.</p>}</div></FormCard></div>;
}

function InfoTab({ data }: { data: any }) {
  const totalPlayers = data.players.length;
  const activePlayers = data.players.filter((player: any) => player.isActive).length;
  const fixedPlayers = data.players.filter((player: any) => player.participantType === "fixed").length;
  const guests = data.players.filter((player: any) => player.participantType === "guest").length;
  const totalMatches = data.matches.length;
  const totalGoals = data.home?.stats?.goals ?? data.scorers.reduce((sum: number, player: any) => sum + (player.goals || 0), 0);
  const latestMatch = data.matches[0];
  const stats = [
    { label: "Jogadores", value: totalPlayers, detail: `${activePlayers} ativos` },
    { label: "Jogadores fixos", value: fixedPlayers, detail: "no elenco" },
    { label: "Convidados", value: guests, detail: "cadastrados" },
    { label: "Partidas", value: totalMatches, detail: "lançadas" },
    { label: "Gols", value: totalGoals, detail: "registrados" },
    { label: "Destaques", value: data.feed.length, detail: "melhor e pior" },
    { label: "Galeria", value: data.gallery.length, detail: "publicações" },
    { label: "Temporadas", value: data.seasons.length, detail: "cadastradas" },
  ];
  return <div className="admin-info"><FormCard title="Resumo da temporada"><div className="admin-info__season"><div><span>Temporada ativa</span><strong>{data.activeSeason?.name || "Nenhuma temporada ativa"}</strong><small>{data.activeSeason?.competitionLabel || "Ative uma temporada para começar"}</small></div>{latestMatch && <div><span>Última partida lançada</span><strong>Preto {latestMatch.blackScore} × {latestMatch.redScore} Vermelho</strong><small>{dateInput(latestMatch.matchDate).split("-").reverse().join("/")}</small></div>}</div><div className="admin-info__grid">{stats.map(stat => <article className="admin-info-stat" key={stat.label}><span>{stat.label}</span><strong>{stat.value}</strong><small>{stat.detail}</small></article>)}</div></FormCard><div className="admin-two-column"><FormCard title="Leitura rápida"><div className="admin-info__notes"><p><strong>Elenco ativo:</strong> {activePlayers} de {totalPlayers || 0} jogadores podem ser escalados.</p><p><strong>Conteúdo publicado:</strong> {data.feed.length} destaques e {data.gallery.length} itens mantêm o feed atualizado.</p><p><strong>Ranking:</strong> os números do painel consideram somente os registros da temporada ativa.</p></div></FormCard><FormCard title="Financeiro"><div className="admin-finance"><div><span>Mensalidades</span><strong>Em preparação</strong><small>O controle de pagamentos será ativado em uma aba financeira própria.</small></div><div><span>Multas</span><strong>Em preparação</strong><small>Futuras multas ficarão vinculadas ao jogador e ao período correspondente.</small></div></div><p className="admin-muted">Nenhuma mensalidade, pagamento ou multa foi registrada ainda. Este bloco não cria cobrança nem valor financeiro nesta fase.</p></FormCard></div></div>;
}

export default function AdminPage() {
  const [tab, setTab] = useState<Tab>("jogadores"); const utils = trpc.useUtils(); const adminQuery = trpc.adminAuth.me.useQuery(undefined, { staleTime: 0, refetchOnMount: "always" }); const logout = trpc.adminAuth.logout.useMutation(); const enabled = Boolean(adminQuery.data); const dataQuery = trpc.admin.data.useQuery(undefined, { enabled }); const data = dataQuery.data as any;
  useEffect(() => { if (data && !data.activeSeason) setTab("editar"); }, [data]);
  if (adminQuery.isLoading) return <PanelFrame><section className="section"><div className="club-container"><div className="empty-state"><LoaderCircle className="spin" /><strong>Verificando acesso</strong></div></div></section></PanelFrame>;
  if (!enabled) return <AdminLogin />;
  if (dataQuery.isLoading || !data) return <PanelFrame><section className="section"><div className="club-container"><div className="empty-state"><LoaderCircle className="spin" /><strong>Organizando o painel</strong></div></div></section></PanelFrame>;
  const leavePanel = async () => { await logout.mutateAsync(); await utils.adminAuth.me.invalidate(); await utils.admin.data.invalidate(); toast.success("Você saiu do painel."); };
  return <PanelFrame><section className="admin-section"><div className="club-container"><div className="admin-toolbar"><nav aria-label="Funções do painel">{tabs.map(item => { const Icon = item.icon; return <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}><Icon size={19} /><span>{item.label}</span></button>; })}</nav><button className="admin-exit" onClick={leavePanel}><LogOut size={16} /> Sair</button></div>{tab === "informacoes" && <InfoTab data={data} />}{tab === "jogadores" && <PlayersTab data={data} />}{tab === "partida" && <MatchTab data={data} />}{tab === "destaques" && <HighlightsTab data={data} />}{tab === "galeria" && <GalleryTab data={data} />}{tab === "editar" && <EditTab data={data} />}{tab === "acessos" && <AccessTab />}</div></section></PanelFrame>;
}
