import { CalendarClock, CircleUserRound, Crown, Pause, Play, XCircle } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

function dateInput(value?: string | Date | null) {
  if (!value) return "";
  const date = new Date(value);
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}

function stageLabel(stage: string) {
  return ({ quarterfinal: "Quartas de final", semifinal: "Semifinal", final: "Final", third_place: "3º lugar" } as Record<string, string>)[stage] || stage;
}

function FixtureEditor({ fixture, entrants, matches }: { fixture: any; entrants: any[]; matches: any[] }) {
  const [date, setDate] = useState(dateInput(fixture.scheduledDate)); const [homeId, setHomeId] = useState(String(fixture.homeEntrantId || "")); const [awayId, setAwayId] = useState(String(fixture.awayEntrantId || "")); const [notes, setNotes] = useState(fixture.notes || ""); const [matchId, setMatchId] = useState(""); const [homePenalty, setHomePenalty] = useState(""); const [awayPenalty, setAwayPenalty] = useState("");
  const update = trpc.admin.copa.updateFixture.useMutation(); const resolve = trpc.admin.copa.resolveFixture.useMutation(); const utils = trpc.useUtils();
  useEffect(() => { setDate(dateInput(fixture.scheduledDate)); setHomeId(String(fixture.homeEntrantId || "")); setAwayId(String(fixture.awayEntrantId || "")); setNotes(fixture.notes || ""); }, [fixture]);
  const save = async () => { try { await update.mutateAsync({ fixtureId: fixture.id, scheduledDate: date, homeEntrantId: homeId ? Number(homeId) : null, awayEntrantId: awayId ? Number(awayId) : null, notes: notes || null }); await utils.admin.data.invalidate(); await utils.club.publicData.invalidate(); toast.success("Confronto atualizado."); } catch (error: any) { toast.error(error.message || "Não foi possível editar o confronto."); } };
  const selectedMatch = matches.find((match: any) => String(match.id) === matchId);
  const close = async () => { if (!selectedMatch) return toast.error("Selecione a partida que foi lançada para este confronto."); try { await resolve.mutateAsync({ fixtureId: fixture.id, matchId: selectedMatch.id, blackScore: selectedMatch.blackScore, redScore: selectedMatch.redScore, homePenaltyScore: selectedMatch.blackScore === selectedMatch.redScore ? Number(homePenalty) : undefined, awayPenaltyScore: selectedMatch.blackScore === selectedMatch.redScore ? Number(awayPenalty) : undefined }); await utils.admin.data.invalidate(); await utils.club.publicData.invalidate(); toast.success("Vencedor avançou no chaveamento."); } catch (error: any) { toast.error(error.message || "Não foi possível encerrar o confronto."); } };
  return <article className={`copa-fixture-admin copa-fixture-admin--${fixture.status}`}><div className="copa-fixture-admin__head"><span>{stageLabel(fixture.stage)} · Jogo {fixture.slotNumber}</span><small>{fixture.status === "completed" ? "Concluído" : fixture.status === "postponed" ? "Adiado" : "Agendado"}</small></div><div className="copa-fixture-admin__form"><label className="admin-field"><span>Domingo</span><input type="date" value={date} onChange={event => setDate(event.target.value)} disabled={fixture.status === "completed"} /></label><label className="admin-field"><span>Capitão preto</span><select value={homeId} onChange={event => setHomeId(event.target.value)} disabled={fixture.status === "completed"}><option value="">A definir</option>{entrants.map(entrant => <option key={entrant.id} value={entrant.id}>{entrant.playerNameSnapshot}</option>)}</select></label><label className="admin-field"><span>Capitão vermelho</span><select value={awayId} onChange={event => setAwayId(event.target.value)} disabled={fixture.status === "completed"}><option value="">A definir</option>{entrants.map(entrant => <option key={entrant.id} value={entrant.id}>{entrant.playerNameSnapshot}</option>)}</select></label></div><label className="admin-field"><span>Observação</span><input value={notes} onChange={event => setNotes(event.target.value)} disabled={fixture.status === "completed"} placeholder="Ex.: adiado por chuva" /></label>{fixture.status !== "completed" && <div className="copa-fixture-admin__actions"><button type="button" className="admin-secondary" onClick={save} disabled={update.isPending}>Salvar chave</button><select value={matchId} onChange={event => setMatchId(event.target.value)}><option value="">Encerrar com partida lançada...</option>{matches.filter((match: any) => !match.copaFixtureId || match.copaFixtureId === fixture.id).map((match: any) => <option key={match.id} value={match.id}>{dateInput(match.matchDate)} · Preto {match.blackScore} × {match.redScore} Vermelho</option>)}</select>{selectedMatch?.blackScore === selectedMatch?.redScore && <><input aria-label="Pênaltis capitão preto" type="number" min="0" value={homePenalty} onChange={event => setHomePenalty(event.target.value)} placeholder="Pênaltis P" /><input aria-label="Pênaltis capitão vermelho" type="number" min="0" value={awayPenalty} onChange={event => setAwayPenalty(event.target.value)} placeholder="Pênaltis V" /></>}<button type="button" className="admin-save" onClick={close} disabled={resolve.isPending}>Avançar vencedor</button></div>}{fixture.winnerEntrantId && <p className="copa-fixture-admin__winner">Classificado: <strong>{entrants.find(entrant => entrant.id === fixture.winnerEntrantId)?.playerNameSnapshot}</strong></p>}</article>;
}

export function CopaAdminTab({ data }: { data: any }) {
  const [title, setTitle] = useState(`Copa ${data.activeSeason?.year || new Date().getFullYear()}`); const [startDate, setStartDate] = useState(dateInput(new Date())); const [cancelReason, setCancelReason] = useState(""); const [postponeDate, setPostponeDate] = useState(dateInput(new Date()));
  const create = trpc.admin.copa.create.useMutation(); const setStatus = trpc.admin.copa.setStatus.useMutation(); const postpone = trpc.admin.copa.postpone.useMutation(); const utils = trpc.useUtils();
  const openCopa = [...(data.copaTournaments || [])].filter((copa: any) => ["draft", "active", "paused"].includes(copa.status)).sort((a: any, b: any) => b.id - a.id)[0];
  const entrants = openCopa ? (data.copaEntrants || []).filter((entrant: any) => entrant.tournamentId === openCopa.id).sort((a: any, b: any) => a.seed - b.seed) : [];
  const fixtures = openCopa ? (data.copaFixtures || []).filter((fixture: any) => fixture.tournamentId === openCopa.id).sort((a: any, b: any) => a.scheduledDate.localeCompare(b.scheduledDate) || a.id - b.id) : [];
  const createCopa = async (event: FormEvent) => { event.preventDefault(); try { await create.mutateAsync({ title, startDate }); await utils.admin.data.invalidate(); toast.success("Copa criada em rascunho. Confira a chave antes de ativar."); } catch (error: any) { toast.error(error.message || "Não foi possível criar a Copa."); } };
  const changeStatus = async (status: "active" | "paused" | "cancelled") => { try { await setStatus.mutateAsync({ tournamentId: openCopa.id, status, reason: status === "cancelled" ? cancelReason : undefined }); await utils.admin.data.invalidate(); await utils.club.publicData.invalidate(); toast.success(status === "active" ? "Copa iniciada; pontos corridos congelados." : status === "paused" ? "Copa pausada." : "Copa cancelada. Os dados da pelada foram preservados."); } catch (error: any) { toast.error(error.message || "Não foi possível atualizar a Copa."); } };
  const delay = async () => { try { await postpone.mutateAsync({ tournamentId: openCopa.id, fromDate: postponeDate, reason: "Rodada cancelada; chave adiada uma semana." }); await utils.admin.data.invalidate(); await utils.club.publicData.invalidate(); toast.success("Próximos jogos foram adiados em uma semana."); } catch (error: any) { toast.error(error.message || "Não foi possível adiar a chave."); } };
  if (!data.activeSeason) return <section className="admin-card"><h2>Modo Copa</h2><p className="admin-muted">Ative uma temporada antes de preparar a Copa.</p></section>;
  if (!openCopa) return <div className="admin-two-column"><section className="admin-card"><h2>Preparar Copa</h2><form className="admin-form" onSubmit={createCopa}><p className="admin-muted">A Copa usa os 8 melhores dos pontos corridos atuais e cria um sorteio em rascunho. Nada fica público até você tocar em “Iniciar Copa”.</p><label className="admin-field"><span>Nome da Copa</span><input required value={title} onChange={event => setTitle(event.target.value)} /></label><label className="admin-field"><span>Primeiro domingo</span><input required type="date" value={startDate} onChange={event => setStartDate(event.target.value)} /></label><button className="admin-save" type="submit" disabled={create.isPending}><Crown size={17} /> Criar chave em rascunho</button></form></section><section className="admin-card"><h2>8 classificados agora</h2><div className="copa-qualifiers">{data.standings.slice(0, 8).map((player: any, index: number) => <div key={player.id}><span>{index + 1}º</span><strong>{player.name}</strong><small>{player.points} pontos · {player.wins} vitórias</small></div>)}</div></section></div>;
  return <div className="copa-admin"><section className="admin-card"><h2>{openCopa.title}</h2><div className="copa-admin__status"><div><span className={`copa-status copa-status--${openCopa.status}`}>{openCopa.status === "draft" ? "Rascunho" : openCopa.status === "active" ? "Copa ativa" : "Copa pausada"}</span><strong>Início programado: {dateInput(openCopa.startDate).split("-").reverse().join("/")}</strong><small>{openCopa.status === "active" ? "Pontos corridos e vitórias estão congelados. Gols, saldo, Melhor, Pior e votos continuam ativos." : "Você pode editar tudo antes de colocar a Copa no ar."}</small></div><div className="copa-admin__status-actions">{openCopa.status !== "active" && <button type="button" className="admin-save" onClick={() => changeStatus("active")} disabled={setStatus.isPending}><Play size={16} /> Iniciar Copa</button>}{openCopa.status === "active" && <button type="button" className="admin-secondary" onClick={() => changeStatus("paused")} disabled={setStatus.isPending}><Pause size={16} /> Pausar</button>}</div></div><div className="copa-entrants-admin">{entrants.map(entrant => <article key={entrant.id}>{entrant.avatarUrlSnapshot ? <img src={entrant.avatarUrlSnapshot} alt="" /> : <CircleUserRound />}{entrant.entityBadgeUrlSnapshot && <img className="copa-entrants-admin__badge" src={entrant.entityBadgeUrlSnapshot} alt="" />}<span><small>{entrant.seed}º classificado</small><strong>{entrant.playerNameSnapshot}</strong><em>{entrant.qualificationPoints} pontos</em></span></article>)}</div></section><section className="admin-card"><h2>Chave editável</h2><p className="admin-muted">Você pode mudar capitães, datas e observações. Depois de salvar uma partida, selecione-a aqui para avançar o vencedor. Empates exigem pênaltis.</p><div className="copa-fixtures-admin">{fixtures.map(fixture => <FixtureEditor key={fixture.id} fixture={fixture} entrants={entrants} matches={data.matches} />)}</div></section><div className="admin-two-column"><section className="admin-card"><h2>Adiamento por chuva</h2><div className="admin-form"><label className="admin-field"><span>Adiar a partir de</span><input type="date" value={postponeDate} onChange={event => setPostponeDate(event.target.value)} /></label><button type="button" className="admin-secondary" onClick={delay} disabled={postpone.isPending}><CalendarClock size={16} /> Empurrar chave uma semana</button></div></section><section className="admin-card"><h2>Cancelar Copa</h2><p className="admin-muted">Cancela somente o torneio. Jogadores, partidas, gols, destaques e dados da pelada permanecem intactos.</p><label className="admin-field"><span>Motivo do cancelamento</span><input value={cancelReason} onChange={event => setCancelReason(event.target.value)} placeholder="Ex.: teste encerrado" /></label><button type="button" className="admin-danger" onClick={() => changeStatus("cancelled")} disabled={setStatus.isPending}><XCircle size={16} /> Cancelar Copa</button></section></div></div>;
}
