create extension if not exists "pgcrypto";

create table if not exists public."adminProfiles" (
  id bigint generated by default as identity primary key,
  "userId" uuid not null unique references auth.users(id) on delete cascade,
  name varchar(120) not null,
  email varchar(320) not null unique,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  year integer not null unique,
  "competitionLabel" varchar(120) not null default 'Pontos corridos',
  "isActive" boolean not null default false,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."footballEntities" (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  category text not null check (category in ('club', 'national_team')),
  "badgeUrl" text,
  "badgeKey" varchar(512),
  source varchar(80),
  "sourceId" varchar(120),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create unique index if not exists football_entities_source_unique on public."footballEntities" (source, "sourceId") where source is not null and "sourceId" is not null;

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  "participantType" text not null check ("participantType" in ('fixed', 'guest')),
  "avatarUrl" text,
  "avatarKey" varchar(512),
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."seasonRegistrations" (
  id bigint generated by default as identity primary key,
  "seasonId" bigint not null references public.seasons(id) on delete cascade,
  "playerId" bigint not null references public.players(id) on delete cascade,
  "footballEntityId" bigint references public."footballEntities"(id) on delete set null,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("seasonId", "playerId")
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  "seasonId" bigint not null references public.seasons(id) on delete cascade,
  "matchDate" date not null,
  "blackScore" integer not null default 0 check ("blackScore" >= 0),
  "redScore" integer not null default 0 check ("redScore" >= 0),
  notes text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."matchParticipants" (
  id bigint generated by default as identity primary key,
  "matchId" bigint not null references public.matches(id) on delete cascade,
  "playerId" bigint not null references public.players(id) on delete restrict,
  "teamColor" text not null check ("teamColor" in ('black', 'red')),
  "isGuest" boolean not null default false,
  "createdAt" timestamptz not null default now(),
  unique ("matchId", "playerId")
);

create table if not exists public."matchGoals" (
  id bigint generated by default as identity primary key,
  "matchId" bigint not null references public.matches(id) on delete cascade,
  "playerId" bigint not null references public.players(id) on delete restrict,
  "teamColor" text not null check ("teamColor" in ('black', 'red')),
  quantity integer not null check (quantity > 0),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("matchId", "playerId")
);

create table if not exists public."roundHighlights" (
  id bigint generated by default as identity primary key,
  "matchId" bigint not null references public.matches(id) on delete cascade,
  kind text not null check (kind in ('best', 'worst')),
  "playerId" bigint not null references public.players(id) on delete restrict,
  "imageUrl" text,
  "imageKey" varchar(512),
  caption text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("matchId", kind)
);

create table if not exists public."galleryItems" (
  id bigint generated by default as identity primary key,
  "seasonId" bigint references public.seasons(id) on delete set null,
  "matchId" bigint references public.matches(id) on delete set null,
  "mediaType" text not null check ("mediaType" in ('image', 'video')),
  "mediaUrl" text not null,
  "mediaKey" varchar(512),
  caption text,
  "capturedAt" date not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['adminProfiles','seasons','footballEntities','players','seasonRegistrations','matches','matchGoals','roundHighlights','galleryItems']
  loop
    execute format('drop trigger if exists set_updated_at on public.%I', table_name);
    execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name);
  end loop;
end;
$$;

create or replace function public.is_amigos_admin() returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public."adminProfiles"
    where "userId" = auth.uid() and "isActive" = true
  );
$$;

grant execute on function public.is_amigos_admin() to anon, authenticated;

alter table public."adminProfiles" enable row level security;
alter table public.seasons enable row level security;
alter table public."footballEntities" enable row level security;
alter table public.players enable row level security;
alter table public."seasonRegistrations" enable row level security;
alter table public.matches enable row level security;
alter table public."matchParticipants" enable row level security;
alter table public."matchGoals" enable row level security;
alter table public."roundHighlights" enable row level security;
alter table public."galleryItems" enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array['seasons','footballEntities','players','seasonRegistrations','matches','matchParticipants','matchGoals','roundHighlights','galleryItems']
  loop
    execute format('drop policy if exists public_read on public.%I', table_name);
    execute format('create policy public_read on public.%I for select using (true)', table_name);
    execute format('drop policy if exists admin_insert on public.%I', table_name);
    execute format('create policy admin_insert on public.%I for insert to authenticated with check (public.is_amigos_admin())', table_name);
    execute format('drop policy if exists admin_update on public.%I', table_name);
    execute format('create policy admin_update on public.%I for update to authenticated using (public.is_amigos_admin()) with check (public.is_amigos_admin())', table_name);
    execute format('drop policy if exists admin_delete on public.%I', table_name);
    execute format('create policy admin_delete on public.%I for delete to authenticated using (public.is_amigos_admin())', table_name);
  end loop;
end;
$$;

drop policy if exists admin_profiles_read on public."adminProfiles";
create policy admin_profiles_read on public."adminProfiles" for select to authenticated using (public.is_amigos_admin());
drop policy if exists admin_profiles_update on public."adminProfiles";
create policy admin_profiles_update on public."adminProfiles" for update to authenticated using (public.is_amigos_admin()) with check (public.is_amigos_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('amigos-media', 'amigos-media', true, 20971520, array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists amigos_media_public_read on storage.objects;
create policy amigos_media_public_read on storage.objects for select using (bucket_id = 'amigos-media');
drop policy if exists amigos_media_admin_insert on storage.objects;
create policy amigos_media_admin_insert on storage.objects for insert to authenticated with check (bucket_id = 'amigos-media' and public.is_amigos_admin());
drop policy if exists amigos_media_admin_update on storage.objects;
create policy amigos_media_admin_update on storage.objects for update to authenticated using (bucket_id = 'amigos-media' and public.is_amigos_admin()) with check (bucket_id = 'amigos-media' and public.is_amigos_admin());
drop policy if exists amigos_media_admin_delete on storage.objects;
create policy amigos_media_admin_delete on storage.objects for delete to authenticated using (bucket_id = 'amigos-media' and public.is_amigos_admin());

create index if not exists matches_season_date_idx on public.matches ("seasonId", "matchDate" desc);
create index if not exists registrations_season_idx on public."seasonRegistrations" ("seasonId");
create index if not exists participants_match_idx on public."matchParticipants" ("matchId");
create index if not exists goals_match_idx on public."matchGoals" ("matchId");
create index if not exists highlights_match_idx on public."roundHighlights" ("matchId");
create index if not exists gallery_season_date_idx on public."galleryItems" ("seasonId", "capturedAt" desc);
