create extension if not exists "pgcrypto";

create table if not exists public."adminProfiles" (
  id bigint generated by default as identity primary key,
  "userId" uuid not null unique references auth.users(id) on delete cascade,
  name varchar(120) not null,
  email varchar(320) not null unique,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  year integer not null unique,
  "competitionLabel" varchar(120) not null default 'Pontos corridos',
  "isActive" boolean not null default false,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."footballEntities" (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  category text not null check (category in ('club', 'national_team')),
  "badgeUrl" text,
  "badgeKey" varchar(512),
  source varchar(80),
  "sourceId" varchar(120),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create unique index if not exists football_entities_source_unique on public."footballEntities" (source, "sourceId") where source is not null and "sourceId" is not null;

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  "participantType" text not null check ("participantType" in ('fixed', 'guest')),
  position varchar(80),
  "avatarUrl" text,
  "avatarKey" varchar(512),
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."seasonRegistrations" (
  id bigint generated by default as identity primary key,
  "seasonId" bigint not null references public.seasons(id) on delete cascade,
  "playerId" bigint not null references public.players(id) on delete cascade,
  "footballEntityId" bigint references public."footballEntities"(id) on delete set null,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("seasonId", "playerId")
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  "seasonId" bigint not null references public.seasons(id) on delete cascade,
  "matchDate" date not null,
  "blackScore" integer not null default 0 check ("blackScore" >= 0),
  "redScore" integer not null default 0 check ("redScore" >= 0),
  notes text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."matchParticipants" (
  id bigint generated by default as identity primary key,
  "matchId" bigint not null references public.matches(id) on delete cascade,
  "playerId" bigint references public.players(id) on delete restrict,
  "guestName" varchar(120),
  "invitedByName" varchar(120),
  "teamColor" text not null check ("teamColor" in ('black', 'red')),
  "isGuest" boolean not null default false,
  "bestVotes" integer not null default 0 check ("bestVotes" >= 0),
  "worstVotes" integer not null default 0 check ("worstVotes" >= 0),
  "createdAt" timestamptz not null default now(),
  unique ("matchId", "playerId")
);

create table if not exists public."matchGoals" (
  id bigint generated by default as identity primary key,
  "matchId" bigint not null references public.matches(id) on delete cascade,
  "playerId" bigint references public.players(id) on delete restrict,
  "guestName" varchar(120),
  "teamColor" text not null check ("teamColor" in ('black', 'red')),
  quantity integer not null check (quantity > 0),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("matchId", "playerId")
);

create table if not exists public."roundHighlights" (
  id bigint generated by default as identity primary key,
  "matchId" bigint not null references public.matches(id) on delete cascade,
  kind text not null check (kind in ('best', 'worst')),
  "playerId" bigint not null references public.players(id) on delete restrict,
  "imageUrl" text,
  "imageKey" varchar(512),
  caption text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("matchId", kind)
);

create table if not exists public."galleryItems" (
  id bigint generated by default as identity primary key,
  "seasonId" bigint references public.seasons(id) on delete set null,
  "matchId" bigint references public.matches(id) on delete set null,
  "mediaType" text not null check ("mediaType" in ('image', 'video')),
  "mediaUrl" text not null,
  "mediaKey" varchar(512),
  caption text,
  "capturedAt" date not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.sponsors (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  "logoUrl" text,
  "logoKey" varchar(512),
  "displayScale" numeric(4,2) not null default 1 check ("displayScale" between 0.70 and 1.60),
  "sortOrder" integer not null default 0 check ("sortOrder" between 0 and 9999),
  "isActive" boolean not null default true,
  "createdBy" uuid references auth.users(id) on delete set null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."copaTournaments" (
  id bigint generated by default as identity primary key,
  "seasonId" bigint not null references public.seasons(id) on delete restrict,
  title varchar(160) not null,
  status text not null default 'draft' check (status in ('draft', 'active', 'paused', 'cancelled', 'completed')),
  "startDate" date not null,
  "standingsFrozenAt" timestamptz,
  "cancelReason" text,
  "createdBy" uuid references auth.users(id) on delete set null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."copaEntrants" (
  id bigint generated by default as identity primary key,
  "tournamentId" bigint not null references public."copaTournaments"(id) on delete cascade,
  "playerId" bigint not null references public.players(id) on delete restrict,
  seed integer not null check (seed between 1 and 8),
  "qualificationPoints" integer not null default 0,
  "qualificationWins" integer not null default 0,
  "qualificationGoals" integer not null default 0,
  "playerNameSnapshot" varchar(120) not null,
  "avatarUrlSnapshot" text,
  "entityNameSnapshot" varchar(160),
  "entityBadgeUrlSnapshot" text,
  "createdAt" timestamptz not null default now(),
  unique ("tournamentId", "playerId"),
  unique ("tournamentId", seed)
);

create table if not exists public."copaFixtures" (
  id bigint generated by default as identity primary key,
  "tournamentId" bigint not null references public."copaTournaments"(id) on delete cascade,
  stage text not null check (stage in ('quarterfinal', 'semifinal', 'final', 'third_place')),
  "slotNumber" integer not null,
  "scheduledDate" date not null,
  status text not null default 'scheduled' check (status in ('scheduled', 'postponed', 'completed', 'cancelled')),
  "homeEntrantId" bigint references public."copaEntrants"(id) on delete restrict,
  "awayEntrantId" bigint references public."copaEntrants"(id) on delete restrict,
  "winnerEntrantId" bigint references public."copaEntrants"(id) on delete restrict,
  "homePenaltyScore" integer check ("homePenaltyScore" >= 0),
  "awayPenaltyScore" integer check ("awayPenaltyScore" >= 0),
  notes text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("tournamentId", stage, "slotNumber")
);

alter table public.matches add column if not exists "countsForStandings" boolean not null default true;
alter table public.matches add column if not exists "copaFixtureId" bigint references public."copaFixtures"(id) on delete set null;
create unique index if not exists matches_copa_fixture_unique on public.matches ("copaFixtureId") where "copaFixtureId" is not null;

create table if not exists public."copaAuditLogs" (
  id bigint generated by default as identity primary key,
  "tournamentId" bigint not null references public."copaTournaments"(id) on delete cascade,
  action varchar(80) not null,
  reason text,
  "beforeData" jsonb,
  "afterData" jsonb,
  "performedBy" uuid references auth.users(id) on delete set null,
  "createdAt" timestamptz not null default now()
);

create table if not exists public."selectionYearOverrides" (
  id bigint generated by default as identity primary key,
  "seasonId" bigint not null references public.seasons(id) on delete restrict,
  role text not null check (role in ('goalkeeper', 'defender', 'midfielder', 'attacker')),
  "slotNumber" integer not null check ("slotNumber" between 1 and 7),
  "playerId" bigint references public.players(id) on delete set null,
  "fieldX" numeric(5,2) not null check ("fieldX" between 5 and 95),
  "fieldY" numeric(5,2) not null check ("fieldY" between 5 and 95),
  "updatedBy" uuid references auth.users(id) on delete set null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("seasonId", role, "slotNumber")
);

create table if not exists public."selectionYearFormations" (
  id bigint generated by default as identity primary key,
  "seasonId" bigint not null unique references public.seasons(id) on delete restrict,
  "goalkeeperCount" integer not null default 1 check ("goalkeeperCount" = 1),
  "defenderCount" integer not null default 2 check ("defenderCount" between 0 and 7),
  "midfielderCount" integer not null default 3 check ("midfielderCount" between 0 and 7),
  "attackerCount" integer not null default 2 check ("attackerCount" between 0 and 7),
  "updatedBy" uuid references auth.users(id) on delete set null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  check ("defenderCount" + "midfielderCount" + "attackerCount" = 7)
);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['adminProfiles','seasons','footballEntities','players','seasonRegistrations','matches','matchGoals','roundHighlights','galleryItems','copaTournaments','copaFixtures','selectionYearOverrides','selectionYearFormations']
  loop
    execute format('drop trigger if exists set_updated_at on public.%I', table_name);
    execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name);
  end loop;
end;
$$;

create or replace function public.is_amigos_admin() returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public."adminProfiles"
    where "userId" = auth.uid() and "isActive" = true
  );
$$;

grant execute on function public.is_amigos_admin() to anon, authenticated;

alter table public."adminProfiles" enable row level security;
alter table public.seasons enable row level security;
alter table public."footballEntities" enable row level security;
alter table public.players enable row level security;
alter table public."seasonRegistrations" enable row level security;
alter table public.matches enable row level security;
alter table public."matchParticipants" enable row level security;
alter table public."matchGoals" enable row level security;
alter table public."roundHighlights" enable row level security;
alter table public."galleryItems" enable row level security;
alter table public.sponsors enable row level security;
alter table public."copaTournaments" enable row level security;
alter table public."copaEntrants" enable row level security;
alter table public."copaFixtures" enable row level security;
alter table public."copaAuditLogs" enable row level security;
alter table public."selectionYearOverrides" enable row level security;
alter table public."selectionYearFormations" enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array['seasons','footballEntities','players','seasonRegistrations','matches','matchParticipants','matchGoals','roundHighlights','galleryItems','selectionYearOverrides','selectionYearFormations']
  loop
    execute format('drop policy if exists public_read on public.%I', table_name);
    execute format('create policy public_read on public.%I for select using (true)', table_name);
    execute format('drop policy if exists admin_insert on public.%I', table_name);
    execute format('create policy admin_insert on public.%I for insert to authenticated with check (public.is_amigos_admin())', table_name);
    execute format('drop policy if exists admin_update on public.%I', table_name);
    execute format('create policy admin_update on public.%I for update to authenticated using (public.is_amigos_admin()) with check (public.is_amigos_admin())', table_name);
    execute format('drop policy if exists admin_delete on public.%I', table_name);
    execute format('create policy admin_delete on public.%I for delete to authenticated using (public.is_amigos_admin())', table_name);
  end loop;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['copaTournaments','copaEntrants','copaFixtures']
  loop
    execute format('drop policy if exists admin_insert on public.%I', table_name);
    execute format('create policy admin_insert on public.%I for insert to authenticated with check (public.is_amigos_admin())', table_name);
    execute format('drop policy if exists admin_update on public.%I', table_name);
    execute format('create policy admin_update on public.%I for update to authenticated using (public.is_amigos_admin()) with check (public.is_amigos_admin())', table_name);
    execute format('drop policy if exists admin_delete on public.%I', table_name);
    execute format('create policy admin_delete on public.%I for delete to authenticated using (public.is_amigos_admin())', table_name);
  end loop;
end;
$$;

drop policy if exists sponsors_public_read on public.sponsors;
create policy sponsors_public_read on public.sponsors for select using ("isActive" = true);
drop policy if exists sponsors_admin_read on public.sponsors;
create policy sponsors_admin_read on public.sponsors for select to authenticated using (public.is_amigos_admin());
drop policy if exists sponsors_admin_insert on public.sponsors;
create policy sponsors_admin_insert on public.sponsors for insert to authenticated with check (public.is_amigos_admin());
drop policy if exists sponsors_admin_update on public.sponsors;
create policy sponsors_admin_update on public.sponsors for update to authenticated using (public.is_amigos_admin()) with check (public.is_amigos_admin());
drop policy if exists sponsors_admin_delete on public.sponsors;
create policy sponsors_admin_delete on public.sponsors for delete to authenticated using (public.is_amigos_admin());

drop policy if exists copa_public_read on public."copaTournaments";
create policy copa_public_read on public."copaTournaments" for select using (status in ('active', 'paused', 'completed'));
drop policy if exists copa_admin_read on public."copaTournaments";
create policy copa_admin_read on public."copaTournaments" for select to authenticated using (public.is_amigos_admin());
drop policy if exists copa_entrants_public_read on public."copaEntrants";
create policy copa_entrants_public_read on public."copaEntrants" for select using (exists (select 1 from public."copaTournaments" t where t.id = "copaEntrants"."tournamentId" and t.status in ('active', 'paused', 'completed')));
drop policy if exists copa_entrants_admin_read on public."copaEntrants";
create policy copa_entrants_admin_read on public."copaEntrants" for select to authenticated using (public.is_amigos_admin());
drop policy if exists copa_fixtures_public_read on public."copaFixtures";
create policy copa_fixtures_public_read on public."copaFixtures" for select using (exists (select 1 from public."copaTournaments" t where t.id = "copaFixtures"."tournamentId" and t.status in ('active', 'paused', 'completed')));
drop policy if exists copa_fixtures_admin_read on public."copaFixtures";
create policy copa_fixtures_admin_read on public."copaFixtures" for select to authenticated using (public.is_amigos_admin());
drop policy if exists copa_audit_admin_read on public."copaAuditLogs";
create policy copa_audit_admin_read on public."copaAuditLogs" for select to authenticated using (public.is_amigos_admin());
drop policy if exists copa_audit_admin_insert on public."copaAuditLogs";
create policy copa_audit_admin_insert on public."copaAuditLogs" for insert to authenticated with check (public.is_amigos_admin());

drop policy if exists admin_profiles_read on public."adminProfiles";
create policy admin_profiles_read on public."adminProfiles" for select to authenticated using (public.is_amigos_admin());
drop policy if exists admin_profiles_update on public."adminProfiles";
create policy admin_profiles_update on public."adminProfiles" for update to authenticated using (public.is_amigos_admin()) with check (public.is_amigos_admin());

-- RLS controla quem pode gravar; estes privilégios permitem que a política seja avaliada.
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('amigos-media', 'amigos-media', true, 20971520, array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists amigos_media_public_read on storage.objects;
create policy amigos_media_public_read on storage.objects for select using (bucket_id = 'amigos-media');
drop policy if exists amigos_media_admin_insert on storage.objects;
create policy amigos_media_admin_insert on storage.objects for insert to authenticated with check (bucket_id = 'amigos-media' and public.is_amigos_admin());
drop policy if exists amigos_media_admin_update on storage.objects;
create policy amigos_media_admin_update on storage.objects for update to authenticated using (bucket_id = 'amigos-media' and public.is_amigos_admin()) with check (bucket_id = 'amigos-media' and public.is_amigos_admin());
drop policy if exists amigos_media_admin_delete on storage.objects;
create policy amigos_media_admin_delete on storage.objects for delete to authenticated using (bucket_id = 'amigos-media' and public.is_amigos_admin());

create index if not exists matches_season_date_idx on public.matches ("seasonId", "matchDate" desc);
create index if not exists registrations_season_idx on public."seasonRegistrations" ("seasonId");
create index if not exists participants_match_idx on public."matchParticipants" ("matchId");
create index if not exists goals_match_idx on public."matchGoals" ("matchId");
create index if not exists highlights_match_idx on public."roundHighlights" ("matchId");
create index if not exists gallery_season_date_idx on public."galleryItems" ("seasonId", "capturedAt" desc);
create index if not exists sponsors_public_order_idx on public.sponsors ("isActive", "sortOrder", id);
create unique index if not exists copa_one_open_tournament_per_season on public."copaTournaments" ("seasonId") where status in ('draft', 'active', 'paused');
create index if not exists copa_entrants_tournament_idx on public."copaEntrants" ("tournamentId", seed);
create index if not exists copa_fixtures_tournament_date_idx on public."copaFixtures" ("tournamentId", "scheduledDate");
