begin;
begin;

create table if not exists public."copaTournaments" (
  id bigint generated by default as identity primary key,
  "seasonId" bigint not null references public.seasons(id) on delete restrict,
  title varchar(160) not null,
  status text not null default 'draft' check (status in ('draft', 'active', 'paused', 'cancelled', 'completed')),
  "startDate" date not null,
  "standingsFrozenAt" timestamptz,
  "cancelReason" text,
  "createdBy" uuid references auth.users(id) on delete set null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."copaEntrants" (
  id bigint generated by default as identity primary key,
  "tournamentId" bigint not null references public."copaTournaments"(id) on delete cascade,
  "playerId" bigint not null references public.players(id) on delete restrict,
  seed integer not null check (seed between 1 and 8),
  "qualificationPoints" integer not null default 0,
  "qualificationWins" integer not null default 0,
  "qualificationGoals" integer not null default 0,
  "playerNameSnapshot" varchar(120) not null,
  "avatarUrlSnapshot" text,
  "entityNameSnapshot" varchar(160),
  "entityBadgeUrlSnapshot" text,
  "createdAt" timestamptz not null default now(),
  unique ("tournamentId", "playerId"),
  unique ("tournamentId", seed)
);

create table if not exists public."copaFixtures" (
  id bigint generated by default as identity primary key,
  "tournamentId" bigint not null references public."copaTournaments"(id) on delete cascade,
  stage text not null check (stage in ('quarterfinal', 'semifinal', 'final', 'third_place')),
  "slotNumber" integer not null,
  "scheduledDate" date not null,
  status text not null default 'scheduled' check (status in ('scheduled', 'postponed', 'completed', 'cancelled')),
  "homeEntrantId" bigint references public."copaEntrants"(id) on delete restrict,
  "awayEntrantId" bigint references public."copaEntrants"(id) on delete restrict,
  "winnerEntrantId" bigint references public."copaEntrants"(id) on delete restrict,
  "homePenaltyScore" integer check ("homePenaltyScore" >= 0),
  "awayPenaltyScore" integer check ("awayPenaltyScore" >= 0),
  notes text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("tournamentId", stage, "slotNumber")
);

alter table public.matches add column if not exists "countsForStandings" boolean not null default true;
alter table public.matches add column if not exists "copaFixtureId" bigint;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'matches_copa_fixture_fk') then
    alter table public.matches add constraint matches_copa_fixture_fk foreign key ("copaFixtureId") references public."copaFixtures"(id) on delete set null;
  end if;
end $$;
create unique index if not exists matches_copa_fixture_unique on public.matches ("copaFixtureId") where "copaFixtureId" is not null;

create table if not exists public."copaAuditLogs" (
  id bigint generated by default as identity primary key,
  "tournamentId" bigint not null references public."copaTournaments"(id) on delete cascade,
  action varchar(80) not null,
  reason text,
  "beforeData" jsonb,
  "afterData" jsonb,
  "performedBy" uuid references auth.users(id) on delete set null,
  "createdAt" timestamptz not null default now()
);

drop trigger if exists set_updated_at on public."copaTournaments";
create trigger set_updated_at before update on public."copaTournaments" for each row execute function public.set_updated_at();
drop trigger if exists set_updated_at on public."copaFixtures";
create trigger set_updated_at before update on public."copaFixtures" for each row execute function public.set_updated_at();

alter table public."copaTournaments" enable row level security;
alter table public."copaEntrants" enable row level security;
alter table public."copaFixtures" enable row level security;
alter table public."copaAuditLogs" enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array['copaTournaments','copaEntrants','copaFixtures']
  loop
    execute format('drop policy if exists admin_insert on public.%I', table_name);
    execute format('create policy admin_insert on public.%I for insert to authenticated with check (public.is_amigos_admin())', table_name);
    execute format('drop policy if exists admin_update on public.%I', table_name);
    execute format('create policy admin_update on public.%I for update to authenticated using (public.is_amigos_admin()) with check (public.is_amigos_admin())', table_name);
    execute format('drop policy if exists admin_delete on public.%I', table_name);
    execute format('create policy admin_delete on public.%I for delete to authenticated using (public.is_amigos_admin())', table_name);
  end loop;
end $$;

drop policy if exists copa_public_read on public."copaTournaments";
create policy copa_public_read on public."copaTournaments" for select using (status in ('active', 'paused', 'completed'));
drop policy if exists copa_admin_read on public."copaTournaments";
create policy copa_admin_read on public."copaTournaments" for select to authenticated using (public.is_amigos_admin());
drop policy if exists copa_entrants_public_read on public."copaEntrants";
create policy copa_entrants_public_read on public."copaEntrants" for select using (exists (select 1 from public."copaTournaments" t where t.id = "copaEntrants"."tournamentId" and t.status in ('active', 'paused', 'completed')));
drop policy if exists copa_entrants_admin_read on public."copaEntrants";
create policy copa_entrants_admin_read on public."copaEntrants" for select to authenticated using (public.is_amigos_admin());
drop policy if exists copa_fixtures_public_read on public."copaFixtures";
create policy copa_fixtures_public_read on public."copaFixtures" for select using (exists (select 1 from public."copaTournaments" t where t.id = "copaFixtures"."tournamentId" and t.status in ('active', 'paused', 'completed')));
drop policy if exists copa_fixtures_admin_read on public."copaFixtures";
create policy copa_fixtures_admin_read on public."copaFixtures" for select to authenticated using (public.is_amigos_admin());
drop policy if exists copa_audit_admin_read on public."copaAuditLogs";
create policy copa_audit_admin_read on public."copaAuditLogs" for select to authenticated using (public.is_amigos_admin());
drop policy if exists copa_audit_admin_insert on public."copaAuditLogs";
create policy copa_audit_admin_insert on public."copaAuditLogs" for insert to authenticated with check (public.is_amigos_admin());

grant select, insert, update, delete on public."copaTournaments", public."copaEntrants", public."copaFixtures", public."copaAuditLogs" to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create unique index if not exists copa_one_open_tournament_per_season on public."copaTournaments" ("seasonId") where status in ('draft', 'active', 'paused');
create index if not exists copa_entrants_tournament_idx on public."copaEntrants" ("tournamentId", seed);
create index if not exists copa_fixtures_tournament_date_idx on public."copaFixtures" ("tournamentId", "scheduledDate");

commit;
