begin;

create table if not exists public."selectionYearOverrides" (
  id bigint generated by default as identity primary key,
  "seasonId" bigint not null references public.seasons(id) on delete restrict,
  role text not null check (role in ('goalkeeper', 'defender', 'midfielder', 'attacker')),
  "slotNumber" integer not null check ("slotNumber" between 1 and 3),
  "playerId" bigint references public.players(id) on delete set null,
  "fieldX" numeric(5,2) not null check ("fieldX" between 5 and 95),
  "fieldY" numeric(5,2) not null check ("fieldY" between 5 and 95),
  "updatedBy" uuid references auth.users(id) on delete set null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("seasonId", role, "slotNumber")
);

drop trigger if exists set_updated_at on public."selectionYearOverrides";
create trigger set_updated_at before update on public."selectionYearOverrides" for each row execute function public.set_updated_at();

alter table public."selectionYearOverrides" enable row level security;
drop policy if exists selection_overrides_public_read on public."selectionYearOverrides";
create policy selection_overrides_public_read on public."selectionYearOverrides" for select using (true);
drop policy if exists selection_overrides_admin_insert on public."selectionYearOverrides";
create policy selection_overrides_admin_insert on public."selectionYearOverrides" for insert to authenticated with check (public.is_amigos_admin());
drop policy if exists selection_overrides_admin_update on public."selectionYearOverrides";
create policy selection_overrides_admin_update on public."selectionYearOverrides" for update to authenticated using (public.is_amigos_admin()) with check (public.is_amigos_admin());
drop policy if exists selection_overrides_admin_delete on public."selectionYearOverrides";
create policy selection_overrides_admin_delete on public."selectionYearOverrides" for delete to authenticated using (public.is_amigos_admin());

grant select, insert, update, delete on public."selectionYearOverrides" to authenticated;
grant select on public."selectionYearOverrides" to anon;
grant usage, select on sequence public."selectionYearOverrides_id_seq" to authenticated;

commit;
