begin;

create table if not exists public."selectionYearFormations" (
  id bigint generated by default as identity primary key,
  "seasonId" bigint not null unique references public.seasons(id) on delete restrict,
  "goalkeeperCount" integer not null default 1 check ("goalkeeperCount" = 1),
  "defenderCount" integer not null default 2 check ("defenderCount" between 0 and 7),
  "midfielderCount" integer not null default 3 check ("midfielderCount" between 0 and 7),
  "attackerCount" integer not null default 2 check ("attackerCount" between 0 and 7),
  "updatedBy" uuid references auth.users(id) on delete set null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  check ("defenderCount" + "midfielderCount" + "attackerCount" = 7)
);

alter table public."selectionYearOverrides" drop constraint if exists "selectionYearOverrides_slotNumber_check";
alter table public."selectionYearOverrides" add constraint selection_year_overrides_slot_number_check check ("slotNumber" between 1 and 7);

drop trigger if exists set_updated_at on public."selectionYearFormations";
create trigger set_updated_at before update on public."selectionYearFormations" for each row execute function public.set_updated_at();

alter table public."selectionYearFormations" enable row level security;
drop policy if exists selection_formations_public_read on public."selectionYearFormations";
create policy selection_formations_public_read on public."selectionYearFormations" for select using (true);
drop policy if exists selection_formations_admin_insert on public."selectionYearFormations";
create policy selection_formations_admin_insert on public."selectionYearFormations" for insert to authenticated with check (public.is_amigos_admin());
drop policy if exists selection_formations_admin_update on public."selectionYearFormations";
create policy selection_formations_admin_update on public."selectionYearFormations" for update to authenticated using (public.is_amigos_admin()) with check (public.is_amigos_admin());
drop policy if exists selection_formations_admin_delete on public."selectionYearFormations";
create policy selection_formations_admin_delete on public."selectionYearFormations" for delete to authenticated using (public.is_amigos_admin());

grant select, insert, update, delete on public."selectionYearFormations" to authenticated;
grant select on public."selectionYearFormations" to anon;
grant usage, select on sequence public."selectionYearFormations_id_seq" to authenticated;

commit;
