begin;

create table if not exists public.sponsors (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  "logoUrl" text,
  "logoKey" varchar(512),
  "displayScale" numeric(4,2) not null default 1 check ("displayScale" between 0.70 and 1.60),
  "sortOrder" integer not null default 0 check ("sortOrder" between 0 and 9999),
  "isActive" boolean not null default true,
  "createdBy" uuid references auth.users(id) on delete set null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index if not exists sponsors_public_order_idx on public.sponsors ("isActive", "sortOrder", id);

drop trigger if exists set_updated_at on public.sponsors;
create trigger set_updated_at before update on public.sponsors for each row execute function public.set_updated_at();

alter table public.sponsors enable row level security;
drop policy if exists sponsors_public_read on public.sponsors;
create policy sponsors_public_read on public.sponsors for select using ("isActive" = true);
drop policy if exists sponsors_admin_read on public.sponsors;
create policy sponsors_admin_read on public.sponsors for select to authenticated using (public.is_amigos_admin());
drop policy if exists sponsors_admin_insert on public.sponsors;
create policy sponsors_admin_insert on public.sponsors for insert to authenticated with check (public.is_amigos_admin());
drop policy if exists sponsors_admin_update on public.sponsors;
create policy sponsors_admin_update on public.sponsors for update to authenticated using (public.is_amigos_admin()) with check (public.is_amigos_admin());
drop policy if exists sponsors_admin_delete on public.sponsors;
create policy sponsors_admin_delete on public.sponsors for delete to authenticated using (public.is_amigos_admin());

grant select, insert, update, delete on public.sponsors to authenticated;
grant select on public.sponsors to anon;
grant usage, select on sequence public.sponsors_id_seq to authenticated;

commit;
